import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const en = {
  driverCenter: 'Driver center', favorites: 'Favorites', favoritesHint: 'All charging stations you saved are collected here.', openMap: 'Open map', favoritesEmpty: 'No favorite stations yet', favoritesEmptyHint: 'Tap the heart on a station card to save it for quick access.', findStations: 'Find stations',
  myBookings: 'My bookings', myBookingsHint: 'View upcoming charging sessions, station locations and routes.', bookingsEmpty: 'No bookings yet', bookingsEmptyHint: 'Choose a station and reserve a convenient charging time.', bookingStateUpcoming: 'Upcoming', bookingStateActive: 'Active', bookingStateCompleted: 'Completed',
  notifications: 'Notifications', unreadNotifications: '{{count}} unread', markAllRead: 'Mark all as read', nextBooking: 'Next booking', enableNotifications: 'Enable reminders', notificationPermissionHint: 'Get a system notification 15 minutes before charging.', notificationsUnsupported: 'System notifications are not supported', notificationsEnabled: 'Charging reminders enabled', notificationsDenied: 'Notification permission was not granted', notificationsEmpty: 'No notifications yet', notificationBookingConfirmed: 'Booking confirmed', notificationBookingCancelled: 'Booking cancelled', notificationBookingReminder: 'Charging starts soon', bookingReminderToast: '{{name}} starts in less than 15 minutes', bookingReminderTitle: 'Charging starts soon', bookingReminderBody: 'Your booking at {{name}} starts in less than 15 minutes.',
  loadingSite: 'Loading charging stations…', map: 'Map', list: 'List', stations: 'Stations', find: 'Find a charger', availableNow: 'available now', search: 'Search by station, street or district', filters: 'Filters', reset: 'Reset all', networks: 'Networks', connectors: 'Connector type',
  availability: 'Availability', all: 'All', statusAvailable: 'Available', statusInUse: 'In use', statusOffline: 'Offline', addStation: 'Add station', live: 'Live data', open: 'Open station', noResults: 'No stations match your filters', tryClearingFilters: 'Try clearing one or more filters.', loadNetworkError: 'We couldn’t load the charging network.', tryAgain: 'Try again',
  nearestFirst: 'Nearest first', shortestQueue: 'Shortest queue', highestPower: 'Highest power', toggleSidebar: 'Toggle sidebar', queue: 'Queue', cars: 'cars', bestQueue: 'Nearest with shortest queue', findingBest: 'Finding the best station…', noWorkingStations: 'No working stations are available', geoUnsupported: 'Your browser does not support geolocation', geoPermissionBest: 'Allow location access to find a station', bestStationMessage: '{{name}}: queue {{queue}} cars, {{distance}} km away',
  locating: 'Finding your location…', locationFound: 'Your location was found', locationDenied: 'Allow access to your location', locationUnsupported: 'Geolocation is not supported', yourLocation: 'Your location', zoomIn: 'Zoom in', zoomOut: 'Zoom out', showMyLocation: 'Show my location', mapLoadError: 'Could not open the map', mapLoadHint: 'Refresh the map — the station list will remain available.', retry: 'Retry', favoriteStation: 'Favorite station',
  myBusiness: 'My business', admin: 'Admin', forBusiness: 'For business', registration: 'Registration', adminPanel: 'Admin panel', toggleTheme: 'Toggle color theme', logout: 'Log out', toggleMenu: 'Toggle menu', homeLabel: 'Charge Tashkent home', roleUser: 'driver', roleBusiness: 'business', roleAdmin: 'admin',
  registerHero: 'Charge Tashkent for everyone', registerHeroText: 'Drivers find chargers while business owners grow their own station network.', featureBooking: 'Booking and live queues', featureOwner: 'Owner dashboard', featureModeration: 'Station verification by an administrator', newAccount: 'New account', chooseAccountType: 'Choose an account type', accountTypeHint: 'The site features will be tailored to your role.', driver: 'Driver', driverHint: 'Search, queue and booking', business: 'Business', businessHint: 'Your own charging stations',
  ownerName: 'Owner name', yourName: 'Your name', nameExample: 'For example, Shokhrukh', companyName: 'Company name', phone: 'Phone', email: 'Email', password: 'Password', passwordMinPlaceholder: 'At least 6 characters', consent: 'I confirm that the information is correct and agree to the service rules.', createBusinessAccount: 'Create business account', createAccount: 'Create account', closedArea: 'Restricted area', adminLogin: 'Administrator login', adminLoginHint: 'Enter the administrator credentials to continue.', enterPassword: 'Enter password', signInAdmin: 'Sign in to admin panel',
  businessAccountCreated: 'Business account created', registrationComplete: 'Registration complete', invalidCredentials: 'Incorrect email or password', adminSignedIn: 'Administrator signed in', validationMin2: 'Enter at least 2 characters', validationEmail: 'Enter a valid email', validationPassword6: 'Enter at least 6 characters', validationConsent: 'Confirm your agreement', validationCompany: 'Enter the company name', validationPhone: 'Enter a phone number', validationRequiredPassword: 'Enter your password',
  businessWorkspace: 'Business workspace', requestManagement: 'Request management', chargingBusiness: 'My charging business', helloBusiness: 'Hello, {{name}}. Add stations and track their publication.', closeForm: 'Close form', allProperties: 'All locations', onMap: 'On the map', beingReviewed: 'Under review', activePorts: 'Active charging ports: {{count}}',
  stationName: 'Station name', stationNameExample: 'e.g. Compass Mall Fast Charge', district: 'District', selectDistrict: 'Select district', streetAddress: 'Street address', addressExample: "e.g. Kichik Halqa Yo'li 17", chargingNetwork: 'Charging network', selectNetwork: 'Select network', selectConnector: 'Select connector', maxPower: 'Maximum power (kW)', currentStatus: 'Current status', addingStation: 'Adding station…', addToMap: 'Add to Tashkent map',
  userRequests: 'User requests', myRequests: 'My requests', station: 'Station', network: 'Network', connector: 'Connector', status: 'Status', actions: 'Actions', noRequestsYet: 'You have no requests yet', viewStation: 'View station', deleteStation: 'Delete station', deleteStationTitle: 'Delete charging station?', deleteStationText: '{{name}} will be removed from the map and station manager. This action cannot be undone.', cancel: 'Cancel', delete: 'Delete',
  requestSent: 'Request sent to the administrator', stationAdded: '{{name}} added to the map', addStationError: 'Could not add station', stationDeleted: 'Station deleted', deleteStationError: 'Could not delete station', validationStationName: 'Enter at least 3 characters', validationDistrict: 'Choose a district', validationAddress: 'Enter a complete address', validationNetwork: 'Choose a network', validationConnector: 'Choose a connector', approvalPending: 'Under review', approvalApproved: 'Approved', approvalRejected: 'Rejected',
  adminControlCenter: 'Admin control center', stationModeration: 'Station moderation', stationModerationHint: 'Review user submissions before publishing them on the shared Charge Tashkent map.', awaitingReview: 'Awaiting review', published: 'Published', userSubmissions: 'User submissions', totalReviews: 'Total reviews', moderationQueue: 'Moderation queue', loadRequestsError: 'Could not load requests.', noDate: 'No date', powerLabel: 'power', connectorLabel: 'connector', operatorLabel: 'operator', owner: 'Owner:', reject: 'Reject', approve: 'Approve', noSubmissions: 'No requests yet', noSubmissionsHint: 'New stations will appear here after users submit them.', stationPublished: 'Station published on the map', requestRejected: 'Request rejected', updateRequestError: 'Could not update the request',
  close: 'Close', bookCharger: 'Book charger', startTime: 'Start time', sessionDuration: 'Session duration', duration: 'Duration', minutes: 'min', freeCancellation: 'Free cancellation', bookingHint: 'The port will be held for 15 minutes after the selected time.', confirmBooking: 'Confirm booking', chooseTime: 'Choose a time', chooseFutureTime: 'Choose a future time', activeBooking: 'Active booking', cancelBooking: 'Cancel booking', bookingConfirmed: 'Charger booked successfully', bookingCancelled: 'Booking cancelled',
  chargeCalculator: 'Charging calculator', smartEstimate: 'Smart estimate', batteryCapacity: 'Battery capacity', currentBattery: 'Current charge', targetBattery: 'Target charge', stationNotFound: 'Station not found', backToMap: 'Back to map', backToChargingMap: 'Back to charging map', chargingNetworkLabel: '{{network}} charging network', getDirections: 'Get directions', copy: 'Copy', addressCopied: 'Address copied', saved: 'Saved', save: 'Save', maxPowerShort: 'Max power', openHours: 'Open', chargingPoints: 'Charging points', connectorStatusHint: 'Live connector status, refreshed moments ago.', upToPower: 'Up to {{power}} kW',
  rating: 'Rating', stationReviews: 'Station reviews', driverFeedback: 'Driver feedback', reviewsCount: 'reviews', yourRating: 'Your rating', yourReview: 'Your review', namePlaceholder: 'How should we call you?', reviewPlaceholder: 'Tell other drivers about charging speed, access and service…', publishReview: 'Publish review', publishing: 'Publishing…', noReviews: 'No reviews yet', firstReview: 'Be the first to share your experience.', reviewPublished: 'Review published', reviewError: 'Could not publish the review', validationRating: 'Choose a rating', validationReviewMin: 'Enter at least 5 characters', validationReviewMax: 'No more than 500 characters', availabilityUpdated: 'Availability updated', updateStationError: 'Could not update this station',
  yourQueuePlace: 'Your place in queue', estimatedWait: 'Estimated wait', joinQueue: 'Join queue', leaveQueue: 'Leave queue', joinedQueue: 'You joined the queue', leftQueue: 'You left the queue', queueError: 'Could not update the queue', liveAvailability: 'Live availability', portsFree: 'of {{total}} ports free', pricingAccess: 'Pricing & access', energyRate: 'Energy rate', parking: 'Parking', freeWhileCharging: 'Free while charging', operator: 'Operator', stationId: 'Station ID', verifiedNetwork: 'Verified network', verifiedNetworkHint: 'Availability and pricing are supplied directly by the {{network}} network.',
  notFoundError: '404 error', roadNotFound: 'Road not found.', routeNotConnected: 'This route isn’t connected to the Charge Tashkent network yet.', returnToMap: 'Return to map', dismiss: 'Dismiss',
}

const ru = {
  driverCenter: 'Личный кабинет водителя', favorites: 'Избранное', favoritesHint: 'Здесь собраны все зарядные станции, которые вы сохранили.', openMap: 'Открыть карту', favoritesEmpty: 'Избранных станций пока нет', favoritesEmptyHint: 'Нажмите на сердечко в карточке станции, чтобы сохранить её для быстрого доступа.', findStations: 'Найти станции',
  myBookings: 'Мои бронирования', myBookingsHint: 'Следите за предстоящими зарядками, адресами станций и маршрутами.', bookingsEmpty: 'Бронирований пока нет', bookingsEmptyHint: 'Выберите станцию и забронируйте удобное время зарядки.', bookingStateUpcoming: 'Предстоит', bookingStateActive: 'Активно', bookingStateCompleted: 'Завершено',
  notifications: 'Уведомления', unreadNotifications: 'Непрочитанных: {{count}}', markAllRead: 'Прочитать все', nextBooking: 'Ближайшая бронь', enableNotifications: 'Включить напоминания', notificationPermissionHint: 'Получать системное уведомление за 15 минут до зарядки.', notificationsUnsupported: 'Системные уведомления не поддерживаются', notificationsEnabled: 'Напоминания о зарядке включены', notificationsDenied: 'Разрешение на уведомления не получено', notificationsEmpty: 'Уведомлений пока нет', notificationBookingConfirmed: 'Бронирование подтверждено', notificationBookingCancelled: 'Бронирование отменено', notificationBookingReminder: 'Скоро начнётся зарядка', bookingReminderToast: '{{name}} — до начала зарядки меньше 15 минут', bookingReminderTitle: 'Скоро начнётся зарядка', bookingReminderBody: 'Ваша бронь на станции {{name}} начнётся меньше чем через 15 минут.',
  loadingSite: 'Загружаем зарядные станции…', map: 'Карта', list: 'Список', stations: 'Станции', find: 'Найдите зарядку', availableNow: 'доступно сейчас', search: 'Поиск по станции, улице или району', filters: 'Фильтры', reset: 'Сбросить', networks: 'Сети', connectors: 'Тип коннектора',
  availability: 'Доступность', all: 'Все', statusAvailable: 'Доступна', statusInUse: 'Занята', statusOffline: 'Не работает', addStation: 'Добавить станцию', live: 'Данные онлайн', open: 'Открыть станцию', noResults: 'По вашему запросу ничего не найдено', tryClearingFilters: 'Попробуйте сбросить один или несколько фильтров.', loadNetworkError: 'Не удалось загрузить сеть зарядных станций.', tryAgain: 'Повторить',
  nearestFirst: 'Сначала ближайшие', shortestQueue: 'Короткая очередь', highestPower: 'Высокая мощность', toggleSidebar: 'Показать или скрыть панель', queue: 'Очередь', cars: 'машин', bestQueue: 'Ближайшая с короткой очередью', findingBest: 'Ищем лучшую станцию…', noWorkingStations: 'Нет работающих станций для выбора', geoUnsupported: 'Ваш браузер не поддерживает геолокацию', geoPermissionBest: 'Разрешите доступ к геопозиции, чтобы найти станцию', bestStationMessage: '{{name}}: очередь {{queue}} машин, {{distance}} км от вас',
  locating: 'Определяем ваше местоположение…', locationFound: 'Ваше местоположение найдено', locationDenied: 'Разрешите доступ к геопозиции', locationUnsupported: 'Геолокация не поддерживается', yourLocation: 'Ваше местоположение', zoomIn: 'Приблизить карту', zoomOut: 'Отдалить карту', showMyLocation: 'Показать моё местоположение', mapLoadError: 'Не удалось открыть карту', mapLoadHint: 'Обновите карту — список станций останется доступен.', retry: 'Повторить', favoriteStation: 'Избранная станция',
  myBusiness: 'Мой бизнес', admin: 'Администратор', forBusiness: 'Для бизнеса', registration: 'Регистрация', adminPanel: 'Админ-панель', toggleTheme: 'Переключить тему', logout: 'Выйти', toggleMenu: 'Открыть меню', homeLabel: 'Главная Charge Tashkent', roleUser: 'водитель', roleBusiness: 'бизнес', roleAdmin: 'администратор',
  registerHero: 'Charge Tashkent для каждого', registerHeroText: 'Водители находят зарядку, а владельцы бизнеса развивают собственную сеть станций.', featureBooking: 'Бронирование и живые очереди', featureOwner: 'Личный кабинет владельца', featureModeration: 'Проверка станций администратором', newAccount: 'Новый аккаунт', chooseAccountType: 'Выберите тип аккаунта', accountTypeHint: 'Возможности сайта будут настроены под вашу роль.', driver: 'Водитель', driverHint: 'Поиск, очередь и бронь', business: 'Бизнес', businessHint: 'Свои зарядные станции',
  ownerName: 'Имя владельца', yourName: 'Ваше имя', nameExample: 'Например, Шохрух', companyName: 'Название компании', phone: 'Телефон', email: 'Email', password: 'Пароль', passwordMinPlaceholder: 'Минимум 6 символов', consent: 'Я подтверждаю корректность данных и согласен с правилами сервиса.', createBusinessAccount: 'Создать бизнес-аккаунт', createAccount: 'Создать аккаунт', closedArea: 'Закрытая зона', adminLogin: 'Вход администратора', adminLoginHint: 'Введите данные администратора для продолжения.', enterPassword: 'Введите пароль', signInAdmin: 'Войти в админ-панель',
  businessAccountCreated: 'Бизнес-аккаунт создан', registrationComplete: 'Регистрация завершена', invalidCredentials: 'Неверный email или пароль', adminSignedIn: 'Вход администратора выполнен', validationMin2: 'Введите минимум 2 символа', validationEmail: 'Введите корректный email', validationPassword6: 'Минимум 6 символов', validationConsent: 'Подтвердите согласие', validationCompany: 'Укажите название компании', validationPhone: 'Укажите номер телефона', validationRequiredPassword: 'Введите пароль',
  businessWorkspace: 'Рабочее пространство бизнеса', requestManagement: 'Управление заявками', chargingBusiness: 'Мой зарядный бизнес', helloBusiness: 'Здравствуйте, {{name}}. Добавляйте станции и отслеживайте их публикацию.', closeForm: 'Закрыть форму', allProperties: 'Все объекты', onMap: 'На карте', beingReviewed: 'Проверяются', activePorts: 'Активных зарядных портов: {{count}}',
  stationName: 'Название станции', stationNameExample: 'Например, Compass Mall Fast Charge', district: 'Район', selectDistrict: 'Выберите район', streetAddress: 'Адрес', addressExample: "Например, Kichik Halqa Yo'li 17", chargingNetwork: 'Зарядная сеть', selectNetwork: 'Выберите сеть', selectConnector: 'Выберите коннектор', maxPower: 'Максимальная мощность (кВт)', currentStatus: 'Текущий статус', addingStation: 'Добавляем станцию…', addToMap: 'Добавить на карту Ташкента',
  userRequests: 'Пользовательские заявки', myRequests: 'Мои заявки', station: 'Станция', network: 'Сеть', connector: 'Коннектор', status: 'Статус', actions: 'Действия', noRequestsYet: 'У вас пока нет заявок', viewStation: 'Открыть станцию', deleteStation: 'Удалить станцию', deleteStationTitle: 'Удалить зарядную станцию?', deleteStationText: '{{name}} будет удалена с карты и из кабинета. Это действие нельзя отменить.', cancel: 'Отмена', delete: 'Удалить',
  requestSent: 'Заявка отправлена администратору', stationAdded: '{{name}} добавлена на карту', addStationError: 'Не удалось добавить станцию', stationDeleted: 'Станция удалена', deleteStationError: 'Не удалось удалить станцию', validationStationName: 'Введите минимум 3 символа', validationDistrict: 'Выберите район', validationAddress: 'Введите полный адрес', validationNetwork: 'Выберите сеть', validationConnector: 'Выберите коннектор', approvalPending: 'На проверке', approvalApproved: 'Одобрено', approvalRejected: 'Отклонено',
  adminControlCenter: 'Центр управления', stationModeration: 'Модерация станций', stationModerationHint: 'Проверяйте заявки пользователей перед публикацией на общей карте Charge Tashkent.', awaitingReview: 'Ожидают проверки', published: 'Опубликовано', userSubmissions: 'Пользовательских заявок', totalReviews: 'Всего отзывов', moderationQueue: 'Очередь модерации', loadRequestsError: 'Не удалось загрузить заявки.', noDate: 'Без даты', powerLabel: 'мощность', connectorLabel: 'коннектор', operatorLabel: 'оператор', owner: 'Владелец:', reject: 'Отклонить', approve: 'Одобрить', noSubmissions: 'Заявок пока нет', noSubmissionsHint: 'Новые станции появятся здесь после отправки пользователями.', stationPublished: 'Станция опубликована на карте', requestRejected: 'Заявка отклонена', updateRequestError: 'Не удалось обновить заявку',
  close: 'Закрыть', bookCharger: 'Забронировать', startTime: 'Время начала', sessionDuration: 'Длительность сеанса', duration: 'Длительность', minutes: 'мин', freeCancellation: 'Бесплатная отмена', bookingHint: 'Порт будет ожидать вас 15 минут после выбранного времени.', confirmBooking: 'Подтвердить бронь', chooseTime: 'Выберите время', chooseFutureTime: 'Выберите будущее время', activeBooking: 'Активная бронь', cancelBooking: 'Отменить бронь', bookingConfirmed: 'Зарядка успешно забронирована', bookingCancelled: 'Бронирование отменено',
  chargeCalculator: 'Калькулятор зарядки', smartEstimate: 'Умный расчёт', batteryCapacity: 'Ёмкость батареи', currentBattery: 'Текущий заряд', targetBattery: 'Желаемый заряд', stationNotFound: 'Станция не найдена', backToMap: 'Вернуться к карте', backToChargingMap: 'Назад к карте зарядок', chargingNetworkLabel: 'Зарядная сеть {{network}}', getDirections: 'Построить маршрут', copy: 'Копировать', addressCopied: 'Адрес скопирован', saved: 'Сохранено', save: 'Сохранить', maxPowerShort: 'Макс. мощность', openHours: 'Часы работы', chargingPoints: 'Зарядные порты', connectorStatusHint: 'Актуальный статус коннекторов, обновлён недавно.', upToPower: 'До {{power}} кВт',
  rating: 'Рейтинг', stationReviews: 'Отзывы о станции', driverFeedback: 'Мнения водителей', reviewsCount: 'отзывов', yourRating: 'Ваша оценка', yourReview: 'Ваш отзыв', namePlaceholder: 'Как к вам обращаться?', reviewPlaceholder: 'Расскажите о скорости зарядки, доступе и обслуживании…', publishReview: 'Опубликовать отзыв', publishing: 'Публикуем…', noReviews: 'Отзывов пока нет', firstReview: 'Станьте первым, кто поделится впечатлением.', reviewPublished: 'Отзыв опубликован', reviewError: 'Не удалось опубликовать отзыв', validationRating: 'Поставьте оценку', validationReviewMin: 'Напишите минимум 5 символов', validationReviewMax: 'Не больше 500 символов', availabilityUpdated: 'Доступность обновлена', updateStationError: 'Не удалось обновить станцию',
  yourQueuePlace: 'Ваше место в очереди', estimatedWait: 'Примерное ожидание', joinQueue: 'Встать в очередь', leaveQueue: 'Выйти из очереди', joinedQueue: 'Вы встали в очередь', leftQueue: 'Вы вышли из очереди', queueError: 'Не удалось обновить очередь', liveAvailability: 'Доступность сейчас', portsFree: 'из {{total}} портов свободно', pricingAccess: 'Стоимость и доступ', energyRate: 'Тариф на энергию', parking: 'Парковка', freeWhileCharging: 'Бесплатно во время зарядки', operator: 'Оператор', stationId: 'ID станции', verifiedNetwork: 'Проверенная сеть', verifiedNetworkHint: 'Данные о доступности и ценах поступают напрямую от сети {{network}}.',
  notFoundError: 'Ошибка 404', roadNotFound: 'Страница не найдена.', routeNotConnected: 'Этот маршрут пока не подключён к сети Charge Tashkent.', returnToMap: 'Вернуться к карте', dismiss: 'Закрыть',
}

const uz = {
  driverCenter: 'Haydovchi kabineti', favorites: 'Sevimlilar', favoritesHint: 'Siz saqlagan barcha quvvatlash stansiyalari shu yerda.', openMap: 'Xaritani ochish', favoritesEmpty: 'Sevimli stansiyalar hali yo‘q', favoritesEmptyHint: 'Tez kirish uchun stansiya kartasidagi yurak belgisini bosing.', findStations: 'Stansiyalarni topish',
  myBookings: 'Band qilishlarim', myBookingsHint: 'Kelgusi quvvatlash, stansiya manzili va yo‘nalishini ko‘ring.', bookingsEmpty: 'Band qilishlar hali yo‘q', bookingsEmptyHint: 'Stansiyani tanlang va qulay quvvatlash vaqtini band qiling.', bookingStateUpcoming: 'Kutilmoqda', bookingStateActive: 'Faol', bookingStateCompleted: 'Tugallangan',
  notifications: 'Bildirishnomalar', unreadNotifications: 'O‘qilmagan: {{count}}', markAllRead: 'Barchasini o‘qish', nextBooking: 'Eng yaqin band qilish', enableNotifications: 'Eslatmalarni yoqish', notificationPermissionHint: 'Quvvatlashdan 15 daqiqa oldin tizim bildirishnomasini oling.', notificationsUnsupported: 'Tizim bildirishnomalari qo‘llanmaydi', notificationsEnabled: 'Quvvatlash eslatmalari yoqildi', notificationsDenied: 'Bildirishnomalarga ruxsat berilmadi', notificationsEmpty: 'Bildirishnomalar hali yo‘q', notificationBookingConfirmed: 'Band qilish tasdiqlandi', notificationBookingCancelled: 'Band qilish bekor qilindi', notificationBookingReminder: 'Quvvatlash tez orada boshlanadi', bookingReminderToast: '{{name}} — quvvatlashgacha 15 daqiqadan kam vaqt qoldi', bookingReminderTitle: 'Quvvatlash tez orada boshlanadi', bookingReminderBody: '{{name}} stansiyasidagi band qilishingiz 15 daqiqadan kam vaqtda boshlanadi.',
  loadingSite: 'Quvvatlash stansiyalari yuklanmoqda…', map: 'Xarita', list: 'Ro‘yxat', stations: 'Stansiyalar', find: 'Quvvatlash joyini toping', availableNow: 'hozir mavjud', search: 'Stansiya, ko‘cha yoki tuman bo‘yicha qidiring', filters: 'Filtrlar', reset: 'Tozalash', networks: 'Tarmoqlar', connectors: 'Ulagich turi',
  availability: 'Mavjudlik', all: 'Barchasi', statusAvailable: 'Mavjud', statusInUse: 'Band', statusOffline: 'Ishlamayapti', addStation: 'Stansiya qo‘shish', live: 'Jonli ma’lumot', open: 'Stansiyani ochish', noResults: 'Filtrlarga mos stansiya topilmadi', tryClearingFilters: 'Bir yoki bir nechta filtrni tozalab ko‘ring.', loadNetworkError: 'Quvvatlash tarmog‘ini yuklab bo‘lmadi.', tryAgain: 'Qayta urinish',
  nearestFirst: 'Avval eng yaqin', shortestQueue: 'Eng qisqa navbat', highestPower: 'Eng yuqori quvvat', toggleSidebar: 'Yon panelni ko‘rsatish yoki yashirish', queue: 'Navbat', cars: 'mashina', bestQueue: 'Eng yaqin, navbati qisqa', findingBest: 'Eng yaxshi stansiya qidirilmoqda…', noWorkingStations: 'Ishlayotgan stansiya topilmadi', geoUnsupported: 'Brauzeringiz geolokatsiyani qo‘llamaydi', geoPermissionBest: 'Stansiyani topish uchun joylashuvga ruxsat bering', bestStationMessage: '{{name}}: navbatda {{queue}} ta mashina, sizdan {{distance}} km',
  locating: 'Joylashuvingiz aniqlanmoqda…', locationFound: 'Joylashuvingiz topildi', locationDenied: 'Joylashuvga kirishga ruxsat bering', locationUnsupported: 'Geolokatsiya qo‘llanmaydi', yourLocation: 'Sizning joylashuvingiz', zoomIn: 'Xaritani yaqinlashtirish', zoomOut: 'Xaritani uzoqlashtirish', showMyLocation: 'Joylashuvimni ko‘rsatish', mapLoadError: 'Xaritani ochib bo‘lmadi', mapLoadHint: 'Xaritani yangilang — stansiyalar ro‘yxati mavjud bo‘lib qoladi.', retry: 'Qayta urinish', favoriteStation: 'Sevimli stansiya',
  myBusiness: 'Mening biznesim', admin: 'Administrator', forBusiness: 'Biznes uchun', registration: 'Ro‘yxatdan o‘tish', adminPanel: 'Admin paneli', toggleTheme: 'Mavzuni almashtirish', logout: 'Chiqish', toggleMenu: 'Menyuni ochish', homeLabel: 'Charge Tashkent bosh sahifasi', roleUser: 'haydovchi', roleBusiness: 'biznes', roleAdmin: 'administrator',
  registerHero: 'Charge Tashkent hamma uchun', registerHeroText: 'Haydovchilar quvvatlash joyini topadi, biznes egalari esa o‘z stansiyalar tarmog‘ini rivojlantiradi.', featureBooking: 'Band qilish va jonli navbatlar', featureOwner: 'Egalar uchun shaxsiy kabinet', featureModeration: 'Stansiyalarni administrator tekshiruvi', newAccount: 'Yangi hisob', chooseAccountType: 'Hisob turini tanlang', accountTypeHint: 'Sayt imkoniyatlari rolingizga moslanadi.', driver: 'Haydovchi', driverHint: 'Qidiruv, navbat va band qilish', business: 'Biznes', businessHint: 'O‘z quvvatlash stansiyalaringiz',
  ownerName: 'Egasining ismi', yourName: 'Ismingiz', nameExample: 'Masalan, Shoxrux', companyName: 'Kompaniya nomi', phone: 'Telefon', email: 'Email', password: 'Parol', passwordMinPlaceholder: 'Kamida 6 ta belgi', consent: 'Ma’lumotlar to‘g‘riligini tasdiqlayman va xizmat qoidalariga roziman.', createBusinessAccount: 'Biznes hisobini yaratish', createAccount: 'Hisob yaratish', closedArea: 'Yopiq hudud', adminLogin: 'Administrator kirishi', adminLoginHint: 'Davom etish uchun administrator ma’lumotlarini kiriting.', enterPassword: 'Parolni kiriting', signInAdmin: 'Admin paneliga kirish',
  businessAccountCreated: 'Biznes hisobi yaratildi', registrationComplete: 'Ro‘yxatdan o‘tish yakunlandi', invalidCredentials: 'Email yoki parol noto‘g‘ri', adminSignedIn: 'Administrator tizimga kirdi', validationMin2: 'Kamida 2 ta belgi kiriting', validationEmail: 'To‘g‘ri email kiriting', validationPassword6: 'Kamida 6 ta belgi kiriting', validationConsent: 'Rozilikni tasdiqlang', validationCompany: 'Kompaniya nomini kiriting', validationPhone: 'Telefon raqamini kiriting', validationRequiredPassword: 'Parolni kiriting',
  businessWorkspace: 'Biznes ish maydoni', requestManagement: 'Arizalarni boshqarish', chargingBusiness: 'Mening quvvatlash biznesim', helloBusiness: 'Salom, {{name}}. Stansiyalar qo‘shing va ularning e’lon qilinishini kuzating.', closeForm: 'Shaklni yopish', allProperties: 'Barcha obyektlar', onMap: 'Xaritada', beingReviewed: 'Tekshirilmoqda', activePorts: 'Faol quvvatlash portlari: {{count}}',
  stationName: 'Stansiya nomi', stationNameExample: 'Masalan, Compass Mall Fast Charge', district: 'Tuman', selectDistrict: 'Tumanni tanlang', streetAddress: 'Manzil', addressExample: "Masalan, Kichik Halqa Yo'li 17", chargingNetwork: 'Quvvatlash tarmog‘i', selectNetwork: 'Tarmoqni tanlang', selectConnector: 'Ulagichni tanlang', maxPower: 'Maksimal quvvat (kW)', currentStatus: 'Joriy holat', addingStation: 'Stansiya qo‘shilmoqda…', addToMap: 'Toshkent xaritasiga qo‘shish',
  userRequests: 'Foydalanuvchi arizalari', myRequests: 'Mening arizalarim', station: 'Stansiya', network: 'Tarmoq', connector: 'Ulagich', status: 'Holat', actions: 'Amallar', noRequestsYet: 'Sizda hozircha arizalar yo‘q', viewStation: 'Stansiyani ochish', deleteStation: 'Stansiyani o‘chirish', deleteStationTitle: 'Quvvatlash stansiyasi o‘chirilsinmi?', deleteStationText: '{{name}} xarita va boshqaruv panelidan o‘chiriladi. Bu amalni bekor qilib bo‘lmaydi.', cancel: 'Bekor qilish', delete: 'O‘chirish',
  requestSent: 'Ariza administratorga yuborildi', stationAdded: '{{name}} xaritaga qo‘shildi', addStationError: 'Stansiyani qo‘shib bo‘lmadi', stationDeleted: 'Stansiya o‘chirildi', deleteStationError: 'Stansiyani o‘chirib bo‘lmadi', validationStationName: 'Kamida 3 ta belgi kiriting', validationDistrict: 'Tumanni tanlang', validationAddress: 'To‘liq manzilni kiriting', validationNetwork: 'Tarmoqni tanlang', validationConnector: 'Ulagichni tanlang', approvalPending: 'Tekshiruvda', approvalApproved: 'Tasdiqlangan', approvalRejected: 'Rad etilgan',
  adminControlCenter: 'Boshqaruv markazi', stationModeration: 'Stansiyalar moderatsiyasi', stationModerationHint: 'Umumiy Charge Tashkent xaritasida e’lon qilishdan oldin foydalanuvchi arizalarini tekshiring.', awaitingReview: 'Tekshiruv kutilmoqda', published: 'E’lon qilingan', userSubmissions: 'Foydalanuvchi arizalari', totalReviews: 'Jami sharhlar', moderationQueue: 'Moderatsiya navbati', loadRequestsError: 'Arizalarni yuklab bo‘lmadi.', noDate: 'Sanasiz', powerLabel: 'quvvat', connectorLabel: 'ulagich', operatorLabel: 'operator', owner: 'Egasi:', reject: 'Rad etish', approve: 'Tasdiqlash', noSubmissions: 'Hozircha arizalar yo‘q', noSubmissionsHint: 'Yangi stansiyalar foydalanuvchilar yuborganidan keyin shu yerda ko‘rinadi.', stationPublished: 'Stansiya xaritada e’lon qilindi', requestRejected: 'Ariza rad etildi', updateRequestError: 'Arizani yangilab bo‘lmadi',
  close: 'Yopish', bookCharger: 'Quvvatlagichni band qilish', startTime: 'Boshlanish vaqti', sessionDuration: 'Seans davomiyligi', duration: 'Davomiyligi', minutes: 'daqiqa', freeCancellation: 'Bepul bekor qilish', bookingHint: 'Port tanlangan vaqtdan keyin 15 daqiqa saqlanadi.', confirmBooking: 'Band qilishni tasdiqlash', chooseTime: 'Vaqtni tanlang', chooseFutureTime: 'Kelajakdagi vaqtni tanlang', activeBooking: 'Faol band qilish', cancelBooking: 'Band qilishni bekor qilish', bookingConfirmed: 'Quvvatlagich muvaffaqiyatli band qilindi', bookingCancelled: 'Band qilish bekor qilindi',
  chargeCalculator: 'Quvvatlash kalkulyatori', smartEstimate: 'Aqlli hisob', batteryCapacity: 'Batareya sig‘imi', currentBattery: 'Hozirgi quvvat', targetBattery: 'Maqsadli quvvat', stationNotFound: 'Stansiya topilmadi', backToMap: 'Xaritaga qaytish', backToChargingMap: 'Quvvatlash xaritasiga qaytish', chargingNetworkLabel: '{{network}} quvvatlash tarmog‘i', getDirections: 'Yo‘nalish olish', copy: 'Nusxalash', addressCopied: 'Manzil nusxalandi', saved: 'Saqlandi', save: 'Saqlash', maxPowerShort: 'Maks. quvvat', openHours: 'Ish vaqti', chargingPoints: 'Quvvatlash portlari', connectorStatusHint: 'Ulagichlarning jonli holati yaqinda yangilandi.', upToPower: '{{power}} kW gacha',
  rating: 'Reyting', stationReviews: 'Stansiya sharhlari', driverFeedback: 'Haydovchilar fikri', reviewsCount: 'sharh', yourRating: 'Bahoyingiz', yourReview: 'Sharhingiz', namePlaceholder: 'Sizga qanday murojaat qilaylik?', reviewPlaceholder: 'Quvvatlash tezligi, kirish va xizmat haqida yozing…', publishReview: 'Sharhni yuborish', publishing: 'Yuborilmoqda…', noReviews: 'Hozircha sharhlar yo‘q', firstReview: 'Birinchi bo‘lib tajribangizni ulashing.', reviewPublished: 'Sharh e’lon qilindi', reviewError: 'Sharhni e’lon qilib bo‘lmadi', validationRating: 'Baho qo‘ying', validationReviewMin: 'Kamida 5 ta belgi yozing', validationReviewMax: '500 belgidan oshmasin', availabilityUpdated: 'Mavjudlik yangilandi', updateStationError: 'Stansiyani yangilab bo‘lmadi',
  yourQueuePlace: 'Navbatdagi o‘rningiz', estimatedWait: 'Taxminiy kutish', joinQueue: 'Navbatga turish', leaveQueue: 'Navbatdan chiqish', joinedQueue: 'Siz navbatga qo‘shildingiz', leftQueue: 'Siz navbatdan chiqdingiz', queueError: 'Navbatni yangilab bo‘lmadi', liveAvailability: 'Hozirgi mavjudlik', portsFree: '{{total}} ta portdan bo‘sh', pricingAccess: 'Narx va kirish', energyRate: 'Energiya tarifi', parking: 'Avtoturargoh', freeWhileCharging: 'Quvvatlash vaqtida bepul', operator: 'Operator', stationId: 'Stansiya ID', verifiedNetwork: 'Tasdiqlangan tarmoq', verifiedNetworkHint: 'Mavjudlik va narxlar to‘g‘ridan-to‘g‘ri {{network}} tarmog‘idan olinadi.',
  notFoundError: '404 xatosi', roadNotFound: 'Sahifa topilmadi.', routeNotConnected: 'Bu yo‘nalish hali Charge Tashkent tarmog‘iga ulanmagan.', returnToMap: 'Xaritaga qaytish', dismiss: 'Yopish',
}

const savedLanguage = localStorage.getItem('charge-language')
const initialLanguage = ['en', 'ru', 'uz'].includes(savedLanguage) ? savedLanguage : 'en'

i18n.use(initReactI18next).init({
  resources: { en: { translation: en }, ru: { translation: ru }, uz: { translation: uz } },
  lng: initialLanguage,
  fallbackLng: 'en',
  supportedLngs: ['en', 'ru', 'uz'],
  interpolation: { escapeValue: false },
})

document.documentElement.lang = initialLanguage
i18n.on('languageChanged', (language) => {
  const normalized = language.split('-')[0]
  document.documentElement.lang = normalized
  localStorage.setItem('charge-language', normalized)
})

export default i18n
